### ISSUE TITLE
0.1.11 breaks something (seen in zwift-second-screen)

### ISSUE THREAD

**Issue by jeroni7100** [Ogadai/zwift-mobile-api#2] opened 2017-03-29 13:06 UTC
It seems like 0.1.11 breaks something which gives more 'Failed to get status' in zwift-second-screen (both 0.0.55 and 0.0.56). 

Example
1008 active riders in world
added 46976 (1)
added 210524 (2)
added 24617 (3)
Failed to get status for 24617

The problems does not occur if I use 0.1.11

**Comment by wiedmann** [comment] 2017-03-29 13:43
I'll take a look at the problem. Are you getting any data at all?

**Comment by jeroni7100** [comment] 2017-03-29 13:55
Yes, for me (46976) and the first rider in the list (210524). In the
example it fails for 24617. I think it is related to the data of this
specific rider, because another test with several followees just now works
just fine when this rider is not on course.

**Comment by Ogadai** [comment] 2017-03-29 13:56
We sometimes get either a 404 or else no data for riders who otherwise appear to be currently riding (no idea why, other than possibly they're just observing).

Previously those failures were handled, but perhaps something about the wrapper has caused it to fail in a different way?

**Comment by Ogadai** [comment] 2017-03-29 13:58
@wiedmann I don't have time to look at it right now, but probably can tomorrow if you haven't figured it out already.

**Comment by jeroni7100** [comment] 2017-03-29 13:59
Yes, I saw (in a test of ZwiftMap) that reading status for this rider
failed consistently AND some other followees on course did not appear
either (but no corresponding log message).

**Comment by jeroni7100** [comment] 2017-03-29 14:01
(maybe it would be an idea to add a logging feature to zwift-mobile-api for
debugging purposes)

**Comment by wiedmann** [comment] 2017-03-29 16:19
I'm having trouble reproducing this issue. I also looked at the profile for rider 24617 and didn't see anything unusual. If you can get the whole exception information, it might help.

I'll keep looking - maybe it has something to do with being part of a group ride or something.

**Comment by Ogadai** [comment] 2017-03-29 16:25
https://github.com/Ogadai/zwift-second-screen gets all the riders you're following, checks which ones are riding (from the all-riders list), and gets regular status updates for each of them (some of which sometimes fail).

Don't spend too much time struggling with it - I'll check it out in the morning.

**Comment by wiedmann** [comment] 2017-03-29 16:37
I fixed one issue like this where a new field I defined as int32 was actually an int64, so it's possible there's an optional field that only comes through under certain circumstances that's defined wrong.

It's not one of the 404s, because those have an error message. I think protobufjs exceptions have a blank message, which is why it just says "Failed to get status for 24617" without any error message.

**Comment by wiedmann** [comment] 2017-03-30 01:20
It is a protobuf issue. Wrong wire type 6 at offset 94. I'll try to figure out which field is wrong.

**Comment by Ogadai** [comment] 2017-03-30 10:15
I think this is fixed now in zwift-mobile-api@0.1.12

It's hard to know for sure because the problem doesn't seem to happen very often. I've also added an exception handler for any possible protobuf errors, and made sure the promise gets correctly rejected so it can be handled properly.

**Closed as completed by Ogadai** 2017-03-30 10:15 UTC
